package com.ashish.signal.ui.components

import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material3.Button
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.Text
import androidx.compose.material3.rememberModalBottomSheetState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.semantics.heading
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.unit.dp
import com.ashish.signal.ui.theme.Dimens

/**
 * Renders the bottom_sheet component type from shared/component-schema.json.
 * [data] is read defensively — the schema is the contract, not the compiler.
 *
 * ModalBottomSheet's default enter/exit slide-and-fade is used as-is — it's
 * the standard Material 3 motion for this surface, so there's no reason to
 * override it.
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun BottomSheetComponent(
    data: Map<String, Any>,
    onDismiss: () -> Unit
) {
    val title = data["title"] as? String ?: ""
    val body = data["body"] as? String ?: ""
    val closeLabel = data["close_label"] as? String ?: "Close"
    val token = data["token"] as? String ?: title
    val iconUrl = data["icon_url"] as? String
    val aiGenerated = data["ai_generated"] as? Boolean ?: false

    ModalBottomSheet(
        onDismissRequest = onDismiss,
        sheetState = rememberModalBottomSheetState()
    ) {
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = Dimens.spaceLg, vertical = Dimens.spaceMd)
        ) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                TokenAvatar(name = token, iconUrl = iconUrl)

                Column(modifier = Modifier.padding(start = Dimens.spaceMd)) {
                    Text(
                        text = title,
                        style = MaterialTheme.typography.headlineSmall,
                        color = MaterialTheme.colorScheme.onSurface,
                        // Lets TalkBack users jump sheet-to-sheet by heading.
                        modifier = Modifier.semantics { heading() }
                    )
                    if (aiGenerated) {
                        Row(
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(Dimens.spaceXs),
                            modifier = Modifier.padding(top = Dimens.spaceXs)
                        ) {
                            Icon(
                                imageVector = Icons.Filled.AutoAwesome,
                                contentDescription = null,
                                tint = MaterialTheme.colorScheme.onSurfaceVariant,
                                modifier = Modifier.size(14.dp)
                            )
                            Text(
                                text = "Generated by AI — may be inaccurate",
                                style = MaterialTheme.typography.labelSmall,
                                color = MaterialTheme.colorScheme.onSurfaceVariant
                            )
                        }
                    }
                }
            }
            Text(
                text = body,
                style = MaterialTheme.typography.bodyLarge,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
                modifier = Modifier.padding(top = Dimens.spaceMd, bottom = Dimens.spaceLg)
            )
            val interactionSource = remember { MutableInteractionSource() }
            Button(
                onClick = onDismiss,
                interactionSource = interactionSource,
                modifier = Modifier
                    .fillMaxWidth()
                    .heightIn(min = Dimens.minTouchTarget)
                    .pressScale(interactionSource)
            ) {
                Text(text = closeLabel)
            }
        }
    }
}
